<?php
/**
 * User: 张世路
 * Date: 2016/11/6
 * Time: 22:17
 */

namespace app\controllers;

use app\models\Address;
use app\models\User;
use yii;

class AddressController extends CommonController
{

    public function beforeAction($action)
    {
        if(empty(Yii::$app->session['username'])){
            $this->redirect(['member/auth']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 添加收货人
     */
    public function actionAdd()
    {
        if(Yii::$app->request->isPost){
            $post = yii::$app->request->post();
            $post['Address']['address'] = $post['Address']['address1'].$post['Address']['address2'];
            $post['Address']['user_id'] = User::find()->where(['useremail'=>Yii::$app->session['username']])->one()->id;

            $addressModel = new Address();
            if($addressModel->load($post) && $addressModel->save()){
                return $this->redirect($_SERVER['HTTP_REFERER']);
            }
            Yii::$app->session->setFlash('info',$addressModel->getFirstErrors());
            return $this->redirect($_SERVER['HTTP_REFERER']);
        }
    }

    /**
     * 删除收货人
     */
    public function actionDel()
    {
        if(Yii::$app->request->isAjax){
            $delAddress_id = Yii::$app->request->get('delAddress_id');
            $addressModel = Address::findOne($delAddress_id);
            $addressModel->delete();
        }
    }

}