<?php
/**
 * User: 张世路
 * Date: 2016/9/25
 * Time: 21:46
 */

namespace app\admin\controllers;

use yii\filters\AccessControl;
use yii\web\Controller;

class BaseController extends Controller{

    /* 用于检测是否登入,只有登入后才能访问后台 */
    /*public function beforeAction($action)
    {
//        if(!\Yii::$app->session->has('admin')){
//            $this->redirect(['public/login']);
//            return false;
//        }
        if(\Yii::$app->admin->isGuest){
            $this->redirect(['public/login']);
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }*/


    /* 用于检测是否登入,只有登入后才能访问后台(使用ACF) */
    public function behaviors()
    {
        return array_merge([
            'accessFilter' => [
                'class'  => AccessControl::className(),
                'user'  => 'admin',
                'only'   => ['*'],//不设置或设置为空或"*"表示所有方法都受管制
                'except' => [],//除此之外
                'rules'  => [
                    [
                        'allow'   => false,//不允许访问
                        'actions' => [],// 不设置或设置为空表示所有,如果要限制单独某些方法,直接写方法名字
                        'roles'   => ['?'],// ? 表示 guest 未登入的
                    ],
                    [
                        'allow'   => true,//允许访问
                        'actions' => [],//不设置或设置为空表示所有,如果要限制单独某些方法,直接写方法名字
                        'roles'   => ['@'],// @ 表示 登入用户
                    ],
                ],
            ],
        ], parent::behaviors());
    }
}